"""optimization_operations"""
from alembic import op
import sqlalchemy as sa

revision = '3712685b1ab1'
down_revision = '2e4666322eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('page_ids', sa.JSON(), nullable=False),
    sa.Column('decision_stage', sa.String(length=30), nullable=False),
    sa.Column('business_value', sa.Integer(), nullable=False),
    sa.Column('business_fit', sa.Integer(), nullable=False),
    sa.Column('content_gap', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('basis', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('page_type', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('next_review_at', sa.String(length=50), nullable=True),
    sa.Column('review_interval_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=False),
    sa.Column('resource', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('requested_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('visible_text', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.Text(), nullable=False),
    sa.Column('headings', sa.JSON(), nullable=False),
    sa.Column('canonical', sa.Text(), nullable=False),
    sa.Column('robots_meta', sa.JSON(), nullable=False),
    sa.Column('json_ld', sa.JSON(), nullable=False),
    sa.Column('robots_txt', sa.JSON(), nullable=False),
    sa.Column('fetch_evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['page_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('primary_change', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('content_version_id', sa.Integer(), nullable=False),
    sa.Column('baseline_batch_id', sa.Integer(), nullable=False),
    sa.Column('retest_batch_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.String(length=50), nullable=False),
    sa.Column('window_end', sa.String(length=50), nullable=False),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.Column('analysis_run_ids', sa.JSON(), nullable=False),
    sa.Column('control_question_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['baseline_batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['retest_batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content_version_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('expected_hash', sa.String(length=64), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('execution_evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_version_id', 'page_id')
    )
    op.create_table('operation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('research_id', sa.Integer(), nullable=True),
    sa.Column('reviewer', sa.String(length=200), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('source_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_job_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('matched_by', sa.String(length=50), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_job_id'], ['publication_jobs.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['page_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('blocked_reason', sa.Text(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('opportunity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('finding_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_actions_page', 'pages', ['page_id'], ['id'])
        batch_op.create_foreign_key('fk_actions_finding', 'page_findings', ['finding_id'], ['id'])
        batch_op.create_foreign_key('fk_actions_opportunity', 'opportunities', ['opportunity_id'], ['id'])

    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_status', sa.String(length=30), nullable=False, server_default="pending"))
        batch_op.add_column(sa.Column('reviewer', sa.String(length=200), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('reviewed_at', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_snapshot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_content_versions_snapshot', 'page_snapshots', ['source_snapshot_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_content_versions_snapshot', type_='foreignkey')
        batch_op.drop_column('source_snapshot_id')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewer')
        batch_op.drop_column('review_status')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_actions_opportunity', type_='foreignkey')
        batch_op.drop_constraint('fk_actions_finding', type_='foreignkey')
        batch_op.drop_constraint('fk_actions_page', type_='foreignkey')
        batch_op.drop_column('finding_id')
        batch_op.drop_column('page_id')
        batch_op.drop_column('opportunity_id')
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('due_at')

    op.drop_table('publication_verifications')
    op.drop_table('operation_rules')
    op.drop_table('publication_jobs')
    op.drop_table('experiments')
    op.drop_table('page_findings')
    op.drop_table('research_revisions')
    op.drop_table('page_snapshots')
    op.drop_table('research')
    op.drop_table('publishers')
    op.drop_table('pages')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
